In [1]:
from datacube import Datacube
cdc = Datacube(config='/g/data/u46/users/ext547/ewater/cambodia_cube/cambodia.conf')

In [2]:
#cdc.list_products()
cdc.list_measurements()

                                                                           aliases  \
product                     measurement
dem_3sec_hydrosheds         elevation                                          NaN
ls5_usgs_sr_scene           blue                                [band_1, sr_band1]
                            green                               [band_2, sr_band2]
                            red                                 [band_3, sr_band3]
                            nir                                 [band_4, sr_band4]
                            swir1                               [band_5, sr_band5]
                            swir2                               [band_7, sr_band7]
                            pixel_qa                                    [pixel_qa]
ls7_usgs_sr_scene           blue                                [band_1, sr_band1]
                            green                               [band_2, sr_band2]
                            red                                 [band_3, sr_band3]
                            nir                                 [band_4, sr_band4]
                            swir1                               [band_5, sr_band5]
                            swir2                               [band_7, sr_band7]
                            sr_atmos_opacity                            [atmos_op]
                            pixel_qa                                    [pixel_qa]
                            radsat_qa                                  [radsat_qa]
                            sr_cloud_qa                                 [cloud_qa]
ls8_usgs_sr_scene           coastal_aerosol                     [band_1, sr_band1]
                            blue                                [band_2, sr_band2]
                            green                               [band_3, sr_band3]
                            red                                 [band_4, sr_band4]
                            nir                                 [band_5, sr_band5]
                            swir1                               [band_6, sr_band6]
                            swir2                               [band_7, sr_band7]
                            pixel_qa                                    [pixel_qa]
                            sr_aerosol        [sr_aerosol_qa, aerosol_qa, aerosol]
                            radsat_qa                                  [radsat_qa]
ls_level2_geomedian_annual  blue                                [band_2, sr_band2]
                            green                               [band_3, sr_band3]
                            red                                 [band_4, sr_band4]
                            nir                                 [band_5, sr_band5]
                            swir1                               [band_6, sr_band6]
                            swir2                               [band_7, sr_band7]
pet_grids_1979_2016         PET                                                NaN
rainfall_grids_1998_2017    rainfall                                           NaN
temperature_grids_1979_2016 temperature                                        NaN

                                                dtype  \
product                     measurement
dem_3sec_hydrosheds         elevation           int16
ls5_usgs_sr_scene           blue                int16
                            green               int16
                            red                 int16
                            nir                 int16
                            swir1               int16
                            swir2               int16
                            pixel_qa           uint16
ls7_usgs_sr_scene           blue                int16
                            green               int16
                            red                 int16
                            nir                 int16
                            swir1               int16
                            swir2               int16
                            sr_atmos_opacity    uint8
                            pixel_qa           uint16
                            radsat_qa           uint8
                            sr_cloud_qa         uint8
ls8_usgs_sr_scene           coastal_aerosol     int16
                            blue                int16
                            green               int16
                            red                 int16
                            nir                 int16
                            swir1               int16
                            swir2               int16
                            pixel_qa           uint16
                            sr_aerosol          uint8
                            radsat_qa          uint16
ls_level2_geomedian_annual  blue                int16
                            green               int16
                            red                 int16
                            nir                 int16
                            swir1               int16
                            swir2               int16
pet_grids_1979_2016         PET               float32
rainfall_grids_1998_2017    rainfall          float32
temperature_grids_1979_2016 temperature       float32

                                                                               flags_definition  \
product                     measurement
dem_3sec_hydrosheds         elevation                                                       NaN
ls5_usgs_sr_scene           blue                                                            NaN
                            green                                                           NaN
                            red                                                             NaN
                            nir                                                             NaN
                            swir1                                                           NaN
                            swir2                                                           NaN
                            pixel_qa          {'snow': {'bits': 4, 'values': {'0': 'no_snow'...
ls7_usgs_sr_scene           blue                                                            NaN
                            green                                                           NaN
                            red                                                             NaN
                            nir                                                             NaN
                            swir1                                                           NaN
                            swir2                                                           NaN
                            sr_atmos_opacity                                                NaN
                            pixel_qa          {'snow': {'bits': 4, 'values': {'0': 'no_snow'...
                            radsat_qa         {'radsat_qa': {'bits': [0, 1, 2, 3, 4, 5, 6, 7...
                            sr_cloud_qa       {'cloud_qa': {'bits': [0, 1, 2, 3, 4, 5, 6, 7]...
ls8_usgs_sr_scene           coastal_aerosol                                                 NaN
                            blue                                                            NaN
                            green                                                           NaN
                            red                                                             NaN
                            nir                                                             NaN
                            swir1                                                           NaN
                            swir2                                                           NaN
                            pixel_qa          {'snow': {'bits': 4, 'values': {'0': 'no_snow'...
                            sr_aerosol        {'aerosol_qa': {'bits': [0, 1, 2, 3, 4, 5, 6, ...
                            radsat_qa         {'radsat_qa': {'bits': [0, 1, 2, 3, 4, 5, 6, 7...
ls_level2_geomedian_annual  blue                                                            NaN
                            green                                                           NaN
                            red                                                             NaN
                            nir                                                             NaN
                            swir1                                                           NaN
                            swir2                                                           NaN
pet_grids_1979_2016         PET                                                             NaN
rainfall_grids_1998_2017    rainfall                                                        NaN
temperature_grids_1979_2016 temperature                                                     NaN

                                                          name  nodata   units
product                     measurement
dem_3sec_hydrosheds         elevation                elevation   -9999       m
ls5_usgs_sr_scene           blue                          blue   -9999       1
                            green                        green   -9999       1
                            red                            red   -9999       1
                            nir                            nir   -9999       1
                            swir1                        swir1   -9999       1
                            swir2                        swir2   -9999       1
                            pixel_qa                  pixel_qa       1       1
ls7_usgs_sr_scene           blue                          blue   -9999       1
                            green                        green   -9999       1
                            red                            red   -9999       1
                            nir                            nir   -9999       1
                            swir1                        swir1   -9999       1
                            swir2                        swir2   -9999       1
                            sr_atmos_opacity  sr_atmos_opacity       0       1
                            pixel_qa                  pixel_qa       1       1
                            radsat_qa                radsat_qa       1       1
                            sr_cloud_qa            sr_cloud_qa       0       1
ls8_usgs_sr_scene           coastal_aerosol    coastal_aerosol   -9999       1
                            blue                          blue   -9999       1
                            green                        green   -9999       1
                            red                            red   -9999       1
                            nir                            nir   -9999       1
                            swir1                        swir1   -9999       1
                            swir2                        swir2   -9999       1
                            pixel_qa                  pixel_qa       1       1
                            sr_aerosol              sr_aerosol       0       1
                            radsat_qa                radsat_qa       1       1
ls_level2_geomedian_annual  blue                          blue   -9999       1
                            green                        green   -9999       1
                            red                            red   -9999       1
                            nir                            nir   -9999       1
                            swir1                        swir1   -9999       1
                            swir2                        swir2   -9999       1
pet_grids_1979_2016         PET                            PET     NaN  mm/day
rainfall_grids_1998_2017    rainfall                  rainfall -9999.9   mm/hr
temperature_grids_1979_2016 temperature            temperature   -9999       C

In [ ]:
# #define temporal range ()
# start_of_epoch = '1999-01-01'
# end_of_epoch =  '1999-01-02'

# query = {'time': (start_of_epoch, end_of_epoch),}

# print(query)

In [20]:
#product_id = 'rainfall_grids_1998_2017'
product_id = 'temperature_grids_1979_2016'

In [21]:
del_datasets = cdc.find_datasets(product=product_id)#,**query)
len(del_datasets)

111040

In [14]:
# # #Remove all/certain files from database. WARNING.
del_eager=[d.id for d in del_datasets]
cdc.index.datasets.archive(del_eager)

In [17]:
print(len(del_datasets))

0